### ISSUE TITLE
Project is too big with all the .txt files

### ISSUE THREAD

**Issue by liamgroen** [MacSuperior/Python-information-retrieval#6]
The project size gets too big with all the .txt files, it would probably also be faster to search through documents as strings in lists than as .txt files

**Comment by dbarenholz** [comment]
On startup of the server/python code read the text files (once) into your desired datastructure.

On another note: it's probably better to make this repository private, and once the deadline of the assignment has passed, make it public. That way, there are less potential plagiarism issues!

**Comment by liamgroen** [comment]
Dataset is loaded in list, can be searched through but this is not yet implemented.
